### ISSUE TITLE
erreur de réécriture dans un répertoire existant

### ISSUE THREAD

**Issue by jaar** [Giwi/camel-dav#1]
On a une GenericFileOperationFailedException si on veut écrire dans un répertoire existant et que l'on a précisé le nom de ce répertoire dans l'option fileName du composant dav.

ex:
from("file:/home/jaar/").to("dav://webstoreUrl/test/?fileName=${date:now:yyyyMMdd}/${file:onlyname}");

La log donne :

11:32:37.533 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - buildDirectory : test, absolute : false
11:32:37.533 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - buildDirectory : test/
11:32:37.533 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - existsFile : test/
11:32:37.565 [Camel (camel-1) thread #196 - file://E://test/] WARN  o.giwi.camel.dav.RemoteFileProducer - Writing file failed with: Unexpected response
11:32:37.565 [Camel (camel-1) thread #196 - file://E://test/] WARN  o.a.c.c.file.GenericFileOnCompletion - Rollback file strategy: org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@cd8e77 for file: GenericFile[E:\test\test2.txt]
11:32:37.565 [Camel (camel-1) thread #196 - file://E://test/] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-M247-52318-1359023525765-0-13 on ExchangeId: ID-M247-52318-1359023525765-0-14). Exhausted after delivery attempt: 1 caught: org.apache.camel.component.file.GenericFileOperationFailedException: Unexpected response
org.apache.camel.component.file.GenericFileOperationFailedException: Unexpected response
    at org.giwi.camel.dav.DavOperations.existsFile(DavOperations.java:69) ~[camel-sardine-0.0.1-SNAPSHOT.jar:na]
    at org.giwi.camel.dav.DavOperations.buildDirectory(DavOperations.java:101) ~[camel-sardine-0.0.1-SNAPSHOT.jar:na]
    at org.apache.camel.component.file.GenericFileProducer.writeFile(GenericFileProducer.java:238) ~[camel-core-2.10.1.jar:2.10.1]
    at org.apache.camel.component.file.GenericFileProducer.processExchange(GenericFileProducer.java:151) ~[camel-core-2.10.1.jar:2.10.1]
    at org.giwi.camel.dav.RemoteFileProducer.process(RemoteFileProducer.java:44) ~[camel-sardine-0.0.1-SNAPSHOT.jar:na]
...

**Comment by Giwi** [comment]
Ce test unitaire passe. 

```
@Test
public void testFromFileToDav() throws Exception {
MockEndpoint mock = getMockEndpoint("mock:result");
mock.expectedMessageCount(2);
template.sendBodyAndHeader("file:src/main/data", "Hello World", Exchange.FILE_NAME, "hello.txt");
Thread.sleep(1000);
template.sendBodyAndHeader("file:src/main/data", "Hello World", Exchange.FILE_NAME, "hello2.txt");
assertMockEndpointsSatisfied();
Thread.sleep(1000);
}

/*
 * (non-Javadoc)
 * 
 * @see org.apache.camel.test.junit4.CamelTestSupport#createRouteBuilder()
 */
@Override
protected RouteBuilder createRouteBuilder() throws Exception {
return new RouteBuilder() {
    @Override
    public void configure() throws Exception {
    from("file:"+ DAV_ROOT_DIR + "/20130403?consumer.initialDelay=5000&autoCreate=false").to("mock:result");
    from("file:src/main/data").to(DAV_URL + "?fileName=${date:now:yyyyMMdd}/${file:onlyname}");
    }
};
}
```
