### ISSUE TITLE
Wiki Page Describing Testing Environment

### ISSUE THREAD

**Issue by mcmonster** [Giwi/camel-dav#3]
The testing framework is expecting certain authentication and directory structures to be in place on the localhost. Could you create a wiki page describing these expectations?

**Comment by Giwi** [comment]
In progress : [https://github.com/BreizhBeans/camel-dav/wiki/Testing-Environment](https://github.com/BreizhBeans/camel-dav/wiki/Testing-Environment)

**Comment by mcmonster** [comment]
Pouvez-vous confirmer le test unitaire "DavLoginTest" doit passer?

**Comment by Giwi** [comment]
le résultat est là : http://giwi.free.fr/docs/camel-dav/surefire-report.html#org.giwi.camel.dav.testDavLoginTest
