### ISSUE TITLE
camel-dav not in sync with camel-code 12.2.x

### ISSUE THREAD

**Issue by krumk** [Giwi/camel-dav#6]
Hello,
I was willing to try the camel-dav component, but it seems that it is using older camel-core.
Do you think you could build a new version which could be used with camel 2.12.x?
I am currently using 2.12.2
Thanks in advance,
Krum

**Comment by Giwi** [comment]
Hi, I'll try to do it as soon as possible.

**Comment by krumk** [comment]
Thank you very much for the fast reply! I am eager to try it. It seems that this is the only webDav component for camel I was able to find so far...

**Comment by Giwi** [comment]
It will be for camel 2.12.3

**Comment by krumk** [comment]
Thank you Xavier.
I would love to try it as soon as available. I have made some adjustment in
the old sources to make them compile, but unfortunately I was not able to
connect to the webdav server. Probably there are some specific settings
that I have to take care about...
Best regards,
Krum

**Comment by Giwi** [comment]
done :)

**Comment by krumk** [comment]
Thank you Xavier,
I am now making some progress with this version.
Unfortunatelly I am hitting the wall with SSL certificates.
Currently I am getting PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find
valid certification path to requested target
How am I suppose to point camel-dav to the right one?

Thanks again,
Krum
